---
- name: Neovim | Setup Neovim Profile Directories(Modular) | file
  file:
    path: "{{ item.0.value }}/{{ item.1.value.appname }}-modular"
    state: directory
    mode: '0755'
  loop: "{{ xdg_config_dirs | dict2items | product(nvim_xdg_modular_profiles | dict2items) | list }}"

- name: Neovim | Setup Neovim Profile Config Directories(Modular) | file
  file:
    path: "{{ xdg_config_dir }}/{{ item.0.value.appname }}-modular/{{ item.1 }}"
    state: directory
    mode: '0755'
  loop: "{{ nvim_xdg_modular_profiles | dict2items | product(nvim_xdg_modular_lua_hierarchy) | list }}"

- name: Neovim | Setup Neovim Notes Directory | file
  file:
    path: "{{ nvim_neorg_dir }}"
    state: directory

- name: Neovim | Setup Neovim Overseer Directories | template
  file:
    path: "{{ xdg_config_dir }}/{{ item.value.appname }}-modular/{{ nvim_overseer_reldir }}"
    state: directory
    mode: '0755'
  loop: "{{ nvim_xdg_modular_profiles | dict2items }}"

- name: Neovim | Setup Neovim Profile Main Config(Modular) | template
  ansible.builtin.template:
    src: "nvim-modular/init.lua.j2"
    dest: "{{ xdg_config_dir }}/{{ item.value.appname }}-modular/init.lua"
  loop: "{{ nvim_xdg_modular_profiles | dict2items }}"

- name: Neovim | Setup Neovim Profile Configs(Modular) | template
  include_tasks: install_neovim_configs_iterate_plugins.yml
  loop: "{{ nvim_xdg_modular_profiles | dict2items }}"
  loop_control:
    loop_var: profile

- name: Neovim | Setup Neovim Project Directories(Modular) | template
  template:
    src: "nvim/{{ cd_project_nvim_dir_database_filename }}.j2"
    dest: "{{ xdg_config_dir }}/{{ item.value['appname'] }}-modular/{{ cd_project_nvim_dir_database_filename }}"
  loop: "{{ nvim_xdg_modular_profiles | dict2items }}"
