---
- name: Setup Broot Config Directory
  file:
    path: "{{ broot_config }}"
    state: directory
    mode: '0755'

- name: Broot | Copies Broot Config | template
  template:
    src: broot/conf.hjson.j2
    dest: "{{ broot_config_file }}"

- name: Broot | Configure Extra Broot Configs | template
  template:
    src: '{{ item.src }}'
    dest: "{{ broot_config }}/{{ item.path  | regex_replace('\\.j2$', '') }}"
  with_filetree: '../templates/broot/broot-plugins'
  when: item.state == 'file'
