---
- name: Setup Yazi Config Directory
  file:
    path: "{{ yazi_config }}"
    state: directory
    mode: "0755"

- name: Yazi | Copies Yazi Config | template
  template:
    src: '{{ item.src }}'
    dest: "{{ yazi_config }}/{{ item.path  | regex_replace('\\.j2$', '') }}"
  with_filetree: '../templates/yazi'
  when: item.state == 'file'
