---
- name: Vars | Set Homebrew Variables | set_fact
  ansible.builtin.set_fact:
    zsh_homebrew_env: "eval \"$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)\""
    bash_homebrew_env: "eval \"$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)\""
