---
ai_adapter_chat: "ollama"
ai_adapter_inline: "{{ ai_adapter_chat }}"
ai_adapter_cmd: "{{ ai_adapter_chat }}"
ollama_port: "11434"
ollama_address: "http://localhost:{{ ollama_port }}"
nvim_codecompanion_adapter_config_ollama: |
        ollama = function()
          return require("codecompanion.adapters").extend("ollama", {
            env = {
              url = "{{ ollama_address }}",
            },
          })
        end,
openai_api_key: "MY_OPEN_AI_API_KEY"
nvim_codecompanion_adapter_config_openai: |
        openai = function()
          return require("codecompanion.adapters").extend("openai", {
            env = {
              api_key = "{{ openai_api_key }}"
            },
          })
        end,
nvim_codecompanion_adapter_config: |
      adapters = {
        {{ nvim_codecompanion_adapter_config_ollama }}
        {{ nvim_codecompanion_adapter_config_openai }}
      },
nvim_ai_companion:
  lazy: |
    {
      "olimorris/codecompanion.nvim",
      dependencies = {
        "nvim-lua/plenary.nvim",
        "nvim-treesitter/nvim-treesitter",
      },
      config = true
    },
  config: |
    require("codecompanion").setup({
      strategies = {
        chat = {
          adapter = "{{ ai_adapter_chat }}",
        },
        inline = {
          adapter = "{{ ai_adapter_inline }}",
        },
        cmd = {
          adapter = "{{ ai_adapter_cmd }}",
        },
      },
      {{ nvim_codecompanion_adapter_config }}
    })
  keymaps: |
    { '<leader>cc', { n = '<cmd>CodeCompanionChat<CR>', }, description = 'CodeCompanion: Chat', },
    { '<leader>ce', { n = '<cmd>lua require("codecompanion").prompt("explain")<CR>', }, description = 'CodeCompanion: Explain', },
