nvim_neorg_dir: "{{ dotfiles_user_home }}/OrgNotes"
nvim_neorg_default:
  packer: |
    use {
        "nvim-neorg/neorg",
        config = function()
            require('neorg').setup {
                load = {
                    ["core.defaults"] = {}, -- Loads default behaviour
                    ["core.concealer"] = {}, -- Adds pretty icons to your documents
                    ["core.keybinds"] = {
                        config = {
                            default_keybinds = true,
                            neorg_leader = ",",
                            hook = function(keybinds)
                              keybinds.unmap("norg", "n", "<CR>")
                              keybinds.unmap("norg", "n", "<M-CR>")
                            end,
                        },
                    },
                    ["core.dirman"] = { -- Manages Neorg workspaces
                        config = {
                            workspaces = {
                                notes = "{{ nvim_neorg_dir }}"
                            },
                        },
                    },
                },
            }
        end,
        run = ":Neorg sync-parsers",
        requires = "nvim-lua/plenary.nvim",
    }
  lazy: |
    {
      "nvim-neorg/neorg",
      build = ":Neorg sync-parsers",
      dependencies = { "nvim-lua/plenary.nvim" },
      ft = 'norg',
      config = function()
        require('neorg').setup({
            load = {
                ["core.defaults"] = {}, -- Loads default behaviour
                ["core.concealer"] = {}, -- Adds pretty icons to your documents
                ["core.keybinds"] = {
                    config = {
                        default_keybinds = true,
                        neorg_leader = ",",
                        hook = function(keybinds)
                          keybinds.unmap("norg", "n", "<CR>")
                          keybinds.unmap("norg", "n", "<M-CR>")
                        end,
                    },
                },
                ["core.dirman"] = { -- Manages Neorg workspaces
                    config = {
                        workspaces = {
                            notes = "{{ nvim_neorg_dir }}"
                        },
                        default_workspace = notes,
                        autochdir = true, -- Automatically change the directory to the current workspace's root every time
                        index = "index.norg", -- The name of the main (root) .norg file
                    },
                },
            },
        })

        vim.wo.foldlevel = 99
        vim.wo.conceallevel = 2
        vim.cmd([[ setlocal spell spelllang=en_us ]])
      end,
    },
nvim_neorg:
  lazy: |
    {
      "vhyrro/luarocks.nvim",
      priority = 1000,
      config = true,
    },
    {
      "nvim-neorg/neorg",
      dependencies = { "luarocks.nvim" },
      lazy = false, -- Disable lazy loading as some `lazy.nvim` distributions set `lazy = true` by default
      version = "*", -- Pin Neorg to the latest stable release
      config = function()
        require("neorg").setup({
          load = {
            ["core.defaults"] = {}, -- Loads default behaviour
            ["core.concealer"] = {}, -- Adds pretty icons to your documents
            ["core.keybinds"] = {
              config = {
                default_keybinds = true,
                neorg_leader = ",",
                hook = function(keybinds)
                  keybinds.unmap("norg", "n", "<CR>")
                  keybinds.unmap("norg", "n", "<M-CR>")
                end,
              },
            },
            ["core.dirman"] = { -- Manages Neorg workspaces
              config = {
                workspaces = {
                  notes = "{{ nvim_neorg_dir }}"
                },
                default_workspace = notes,
                autochdir = true, -- Automatically change the directory to the current workspace's root every time
                index = "index.norg", -- The name of the main (root) .norg file
              },
            },
          },
        })
        vim.wo.foldlevel = 99
        vim.wo.conceallevel = 2
        vim.cmd([[ setlocal spell spelllang=en_us ]])
      end,
    },
  config: ""
  keymaps: ""
nvim_neorg_legacy:
  lazy: |
    {
      "nvim-neorg/neorg",
      lazy = false,
      version = "v7.0.0",
      dependencies = { "nvim-lua/plenary.nvim" },
      ft = 'norg',
      config = function()
        require('neorg').setup({
            load = {
                ["core.defaults"] = {}, -- Loads default behaviour
                ["core.concealer"] = {}, -- Adds pretty icons to your documents
                ["core.keybinds"] = {
                    config = {
                        default_keybinds = true,
                        neorg_leader = ",",
                        hook = function(keybinds)
                          keybinds.unmap("norg", "n", "<CR>")
                          keybinds.unmap("norg", "n", "<M-CR>")
                        end,
                    },
                },
                ["core.dirman"] = { -- Manages Neorg workspaces
                    config = {
                        workspaces = {
                            notes = "{{ nvim_neorg_dir }}"
                        },
                        default_workspace = notes,
                        autochdir = true, -- Automatically change the directory to the current workspace's root every time
                        index = "index.norg", -- The name of the main (root) .norg file
                    },
                },
            },
        })

        vim.wo.foldlevel = 99
        vim.wo.conceallevel = 2
        vim.cmd([[ setlocal spell spelllang=en_us ]])
      end,
    },
  config: ""
  keymaps: ""
