---
nvim_legendary_default:
  packer: |
    use { 'mrjones2014/legendary.nvim',
      requires = {
        'folke/which-key.nvim',
      },
    }
  lazy: |
    {
      'mrjones2014/legendary.nvim',
      version = 'v2.13.6',
      priority = 10000,
      lazy = false,
      dependencies = {
        'kkharji/sqlite.lua',
        'folke/which-key.nvim',
      },
    },
  config: |
    require('which-key').setup({
      triggers = {'<leader>', 'g'},
      triggers_blacklist = {
        n = { '<C-w>', '<C-g>' },
        v = { '<C-w>', '<C-g>' },
      },
    })
  keymaps: |
    { '<CR>', {
        n = ':',
      },
      description = 'Enter Ex Commands',
    },
    { ':', {
        n = ',',
      },
      description = 'Remap Repeat',
    },
    { '<leader>l', {
        n = ':Legendary<CR>',
      },
      description = 'List Legendary Commands',
    },
nvim_legendary:
  lazy: |
    {
      'mrjones2014/legendary.nvim',
      version = 'v2.13.6',
      priority = 10000,
      lazy = false,
      dependencies = {
        'kkharji/sqlite.lua',
        'folke/which-key.nvim',
      },
      config = function ()
        require('which-key').setup({
          triggers = {'<leader>', 'g'},
          triggers_blacklist = {
            n = { '<C-w>', '<C-g>' },
            v = { '<C-w>', '<C-g>' },
          },
        })
      end,
    },
  config: ""
  keymaps: |
    { '<CR>', {
        n = ':',
      },
      description = 'Vim: Enter Ex Commands',
    },
    { ':', {
        n = ',',
      },
      description = 'Vim: Remap Repeat',
    },
    { '<leader>l', {
        n = ':Legendary<CR>',
      },
      description = 'Legendary: List Commands',
    },
    {
      '<C-]>', {
        n = ':noh<CR>',
      },
      description = 'Vim: Clear Search Result',
    },
