atuin_exe: "atuin"
astgrep_exe: "sg"
bat_exe: "bat"
broot_exe: "broot"
bottom_exe: "btm"
choose_exe: "choose"
counts_exe: "counts"
delta_exe: "delta"
difftastic_exe: "difft"
diffr_exe: "diffr"
dust_exe: "dust"
eva_exe: "eva"
erdtree_exe: "erd"
exa_exe: "exz"
fd_exe: "fd"
felix_exe: "fx"
fend_exe: "fend"
grex_exe: "grex"
gitui_exe: "gitui"
hyperfine_exe: "hyperfine"
joshuto_exe: "joshuto"
just_exe: "just"
lsd_exe: "lsd"
macchina_exe: "macchina"
mprocs_exe: "mprocs"
navi_exe: "navi"
nu_exe: "nu"
carapace_exe: "carapace"
ouch_exe: "ouch"
procs_exe: "procs"
rg_exe: "rg"
rnr_exe: "rnr"
sd_exe: "sd"
skim_exe: "sk"
starship_exe: "starship"
wikitui_exe: "wiki-tui"
xcp_exe: "xcp"
xplr_exe: "xplr"
yazi_exe: "yazi"
zellij_exe: "zellij"
zoxide_exe: "zoxide"
fzf_exe: "fzf"
nvim_exe: "nvim"
