---
yazi_config: "{{ xdg_config_dir }}/yazi"
yazi_config_file: "{{ yazi_config }}/yazi.toml"
yazi_plugin_dir: "{{ yazi_config }}/plugins"
yazi_plugins:
  bat:
    name: bat
    url: "https://github.com/mgumz/yazi-plugin-bat"
