---
system_home: "/home"
dotfiles_home: "{{ ansible_env.HOME }}"
dotfiles_user_home: "{{ ansible_env.HOME }}"
default_home_local: "{{ dotfiles_user_home }}/.local"
tool_install_dir: "{{ default_home_local }}"
tool_install_bin: "{{ tool_install_dir }}/bin"
tool_system_path: "{{ tool_install_bin }}/"
bin_directory: "{{ tool_install_bin }}/"
interactive_shell_cmd: "nu"
interactive_shell: "{{ nu_exe }}"
command_shell: "/bin/bash"
gcc_exe: /usr/bin/gcc
gpp_exe: /usr/bin/g++
make_exe: "make"
dot_download_dir: "{{ tool_install_dir }}/downloads"
direnv_exe: "{{ tool_system_path }}direnv"
homebrew_install_path: "{{ system_home }}/linuxbrew/.linuxbrew"
homebrew_path: "{{ homebrew_install_path }}/bin"
homebrew_install_path_macos: "/opt/homebrew"
homebrew_path_macos: "{{ homebrew_install_path_macos }}/bin"
